export const homeObjectOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "premuim service",
  headLine: "Guaranteed Enrollment in Over 100 Companies",
  description:
    "Get Access to our exclusive app that opens the gate to train with Experts in over 100 different companies in different fields",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../images/work.svg").default,
  alt: "car",
  dark: true,
  primary: true,
  darkText: false,
  link: "/signup",
};
export const homeObjectTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Career support",
  headLine: "Real time support through dedicated teams",
  description:
    "Get real time feedback and Career support through recommened paths studied by our teams to help you jump starting your career",
  buttonLabel: "Learn more",
  imgStart: true,
  img: require("../../images/cv.svg").default,
  alt: "car",
  dark: false,
  primary: false,
  darkText: true,
  link: "/",
};
